/*************** AUTO GENERATED BY REMOTE CONTROL MODULE ***************/

var config = 
{
  address: '0.0.0.0',
  port: 8000,
  ipWhitelist: [],
  modules: [
    {
      module: 'alert',
      config: {}
    },
    {
      module: 'updatenotification',
      position: 'top_bar',
      config: {}
    },
    {
      module: 'MMM-Wallpaper',
      position: 'fullscreen_below',
      config: {
        slideInterval: 60000
      }
    },
  
    {
      module: 'MMM-Remote-Control',
      config: {
        showModuleApiMenu: true,
        secureEndpoints: true
      }
    },
    {
    module: 'MMM-voice',
    position: 'bottom_bar',
    config: {
        microphone: 0,
        keyword: 'MAGIC MIRROR',
        timeout: 15
    }
},
  
    {
      module: 'MMM-DailyPokemon',
      position: 'top_center',
      header: '',
      config: {
        updateInterval: 600000,
        language: 'zh-Hans',
        nameSize: 26,
        grayscale: false,
        gbaMode: false
      }
    },
    {
      module: 'clock',
      position: 'top_left',
      config: {}
    },
    {
      module: 'calendar',
      header: 'CN Holidays',
      position: 'top_left',
      config: {
        calendars: [
          {
            symbol: 'calendar-check',
            url: 'https://www.calendarlabs.com/ical-calendar/ics/40/China_Holidays.ics'
          }
        ]
      }
    },
    {
      module: 'compliments',
      position: 'lower_third',
      config: {}
    },
    {
      module: 'currentweather',
      position: 'top_right',
      config: {
        weatherProvider: 'openweathermap',
        type: 'current',
        location: 'Wenzhou',
        locationID: '1791388',
        appid: 'eb9d77cb489ecf8b7651b98e075e5171'
      }
    },
    {
      module: 'weatherforecast',
      position: 'top_right',
      header: 'Weather Forecast',
      config: {
        weatherProvider: 'openweathermap',
        type: 'forecast',
        location: 'Wenzhou',
        locationID: '1791388',
        appid: 'eb9d77cb489ecf8b7651b98e075e5171'
      }
    },
    {
      module: 'newsfeed',
      position: 'bottom_bar',
      config: {
        feeds: [
          {
            title: 'Renming News - Global',
            url: 'http://www.people.com.cn/rss/world.xml'
          }
        ]
      }
    }
  ],
  useHttps: false,
  httpsPrivateKey: '',
  httpsCertificate: '',
  locale: 'en-US'
}

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== 'undefined') {module.exports = config;}
